# Generated by Django 5.1.3 on 2024-12-02 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanreport',
            name='created_at',
        ),
        migrations.AddField(
            model_name='scanreport',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanreport',
            name='url',
            field=models.URLField(),
        ),
    ]
